# Generated by Django 3.2.9 on 2021-11-14 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaraunt', '0002_auto_20211114_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email_en',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message_en',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email_uz',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message_uz',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name_uz',
        ),
    ]
